### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by josealberto4444** [axelboc/anki-ultimate-geography#161] opened 2019-10-22 13:23 UTC
I think I could manage to do the Spanish translation of this deck. Is that OK? =)

**Comment by josealberto4444** [comment] 2019-10-22 13:50
Taking a look at how the translation works, and regarding how git works, I think it's better to wait until the French translation is finally revised and merged. Do you agree?

**Comment by aplaice** [comment] 2019-10-22 16:56
Thanks for offering!

> Taking a look at how the translation works, and regarding how git works, I think it's better to wait until the French translation is finally revised and merged. Do you agree?

On the whole, yes. (In principle, "merging" the two translated versions would be a matter of copying several columns in a spreadsheet and rebasing, but it's unnecessary additional work and it increases the scope for errors. Unless you have a strong preference for doing the translation now (for whatever reason), it would indeed be better to wait.)

An improved translation system is on the radar (#143), but not yet designed or implemented...

**Comment by josealberto4444** [comment] 2019-10-23 12:07
I will wait, yes, no problem. =)

**Comment by josealberto4444** [comment] 2019-11-20 19:59
I will start with this in the following days, as the French translation is already merged. =D

**Comment by josealberto4444** [comment] 2019-11-20 22:09
I have a question: where are the strings as "Location", "Capital", etc. translated? I cannot find them in `data.csv`.

**Comment by josealberto4444** [comment] 2019-11-20 23:07
Another question: what do you use for editing `data.csv` creating new columns or things like that?

I was using LibreOffice, but when I save the csv I can only choose to put between quotes all strings or none, while the original file uses quotes only when the string has spaces.

**Comment by aplaice** [comment] 2019-11-21 07:48
> I have a question: where are the strings as "Location", "Capital", etc. translated? I cannot find them in data.csv.

They aren't currently. (This is ["on the radar"](https://github.com/axelboc/anki-ultimate-geography/issues/143#issuecomment-546508579), but not yet implemented.) 

The strings are only present in the [templates](https://github.com/axelboc/anki-ultimate-geography/tree/master/src/templates) (e.g. [Capital -> Country](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/templates/Capital%20-%20Country.html)) so, in the meantime they could, in principle, be translated by the end-user in their own decks. (Yes, I know that that's horrible and abominably ineffective...)

> I was using LibreOffice, but when I save the csv I can only choose to put between quotes all strings or none, while the original file uses quotes only when the string has spaces.

The quotation convention is caused by the fact that `anki-dm` (which is used to convert between the CSV and CrowdAnki's format) is written in PHP. PHP quotes CSVs very weirdly, in the way you noticed here,  like no other tool. Google docs, Excel and all other programming languages that I'm aware of, do what LibreOffice does. (Since the CSV specification is under-specified, PHP's behaviour isn't strictly violating standards, but it's still awkward...)

The workaround currently used here, is to [run `composer index` before committing](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md#quotes-normalisation), which makes `anki-dm` read the CSV in, and then write it back out, using PHP's weird quotation convention.

If you're strongly opposed to doing this, for whatever reason, then in principle somebody could do it for you before the final merge. (In the meantime, though, you might get scary, if ultimately harmless, failed checks for your pull-requests.)

**Comment by josealberto4444** [comment] 2019-12-06 15:00
> They aren't currently. (This is ["on the radar"](https://github.com/axelboc/anki-ultimate-geography/issues/143#issuecomment-546508579), but not yet implemented.)
> 
> The strings are only present in the [templates](https://github.com/axelboc/anki-ultimate-geography/tree/master/src/templates) (e.g. [Capital -> Country](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/templates/Capital%20-%20Country.html)) so, in the meantime they could, in principle, be translated by the end-user in their own decks. (Yes, I know that that's horrible and abominably ineffective...)

OK. No problem, then. Future work. =)

> The workaround currently used here, is to edit `data.csv` with whatever tool you want and then [run `composer index` before committing](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md#quotes-normalisation), which makes `anki-dm` read the CSV in, and then write it back out, using PHP's weird quotation convention.

Ah, sorry. I promise I read all guidelines before proposing to do the Spanish translation (=P), but I didn't understand that and just skipped it. Now I fully understood it and I've just set up php and composer. I did some tests and everything works as expected. Thanks for your help!

Also, to keep you informed, I will have translated approximately a third of the deck by the end of the day. It's been a ton of work these weeks and I didn't have time until yesterday. Also, translating is more work than I thought, I'm finding lots of issues in `data.csv` and I'm keeping track of them for fixing after the Spanish translation is merged (or I'll get crazy, haha). =)

**Comment by josealberto4444** [comment] 2020-01-28 11:55
Sorry about being out for a long time. I was finishing my PhD Thesis and it was extremely exhausting.

Good news: I have finished writing it and decided to give me a free week before getting the defence ready, so I think I will finish the translation this week (or, maybe, at the beginning of next week).

By the way, will you attend FOSDEM? I will be there this weekend. =)

**Comment by axelboc** [comment] 2020-01-28 13:30
Thanks for the update. Good luck with your thesis defence! I won't be at FOSDEM, but it looks awesome. ☺️

**Comment by josealberto4444** [comment] 2020-02-09 13:01
I have a doubt. In Spanish, both "Sint Maarten" and "Saint Martin" are "San Martín". Seeing the hint, one could tell if it's a part of the Netherlands or France, but now, after fixing #164, there is no hint in certain cards.

Should I add the country at the end of the name of the territory as "San Martín (Francia)" and "San Martín (Países Bajos)"?

**Comment by josealberto4444** [comment] 2020-02-09 15:46
OK, so I submitted the pull request.

I have found several issues (too many for opening an issue for each of them) while doing the translation. If you agree, I will post them here and so we can discuss after merging the PR.

**Comment by aplaice** [comment] 2020-02-09 15:49
> Should I add the country at the end of the name of the territory as "San Martín (Francia)" and "San Martín (Países Bajos)"?

I think that that's the best solution, especially since that's what Spanish Wikipedia does. Obviously @axelboc might override that.

> I'm going to finish the translation today

Hooray!

<hr/>

> By the way, the same problem happens in French translation.

Ooops, we didn't catch that. Thanks for pointing it out! Fortunately, it's the only such issue in the French translation. There's also one "copy-pasto" in the Norwegian version (Argentina/Chile). 

<details>
(You can check with:

```bash
for i in `seq 2 5`; do 
    csvtool cols "$i" src/data.csv | head -n 1
    csvtool cols "$i" src/data.csv | sort | uniq -c | grep -v 1
done
```
)
</details> 

(I'll fix these, though they probably should be only merged after the Spanish translation, to minimise merge conflicts.)

**Comment by josealberto4444** [comment] 2020-02-09 16:39
> I think that that's the best solution, especially since that's what Spanish Wikipedia does. Obviously @axelboc might override that.

I put that following your emoji reaction and submitted the PR. =P

> (I'll fix these, though they probably should be only merged after the Spanish translation, to minimise merge conflicts.)

Thank you!

> Please do!

OK, so get ready for a long reply. This is copied from the document I did while translating:

While doing the Spanish translation, I found the following issues. Some of them are very straightforward to fix, but others are more difficult.

1. Some strings do not come from a translation (I think some of them make sense, but I don't understand most of them and I wonder why they are there):

    1. United Kingdom > Country info:nb
	1. Greenland > Capital info:nb
	1. Finland > Capital info:nb
	1. Moldova > Country info:de
	1. Montenegro > Capital info:nb
	1. Netherlands > Capital info:nb
	1. Ukraine > Capital info:nb
	1. China > Country info:nb
	1. Myanmar > Capital info:nb
	1. Mongolia > Capital info:nb
	1. Palestine > Capital info:nb (I think it's related with the double capital issue)
	1. Turkmenistan > Capital info:nb
	1. Solomon Islands > Country info:de
	1. Suriname > Country info:de
	1. United States of America > Country info:nb
	1. Kiribati > Capital info:nb
	1. Tuvalu > Capital info:nb
	1. Pacific Ocean > Country info:de
	1. Atlantic Ocean > Country info:de
	1. Indian Ocean > Country info:nb
	1. Arctic Ocean > Country info:de
	1. White Sea > Country info:de
	1. White Sea > Country info:nb
	1. Norwegian Sea > Country info:de
	1. Baltic Sea > Country info:de
	1. Baltic Sea > Country info:nb
	1. Bay of Biscay > Country info:de
	1. Aegean Sea > Country info:de
	1. Balkan Peninsula > Country info:de
	1. Balkan Peninsula > Country info:nb
	1. Caspian Sea > Country info:de
	1. Arabian Sea > Country info:nb
	1. Persian Gulf > Country info:de
	1. Persian Gulf > Country info:nb
	1. Sea of Galilee > Country info:nb
	1. British Indian Ocean Territory > Capital hint:de

1. There are some sentences ended with a period and some that are not in the same field, without consistency. Which fields should end with a period and which of them shouldn't?
1. There are some flag similarities where all countries are separated by commas and some other where the last country is separated by "and". I translated the exact English string, but other languages use always commas even if the English string doesn't.
1. For Iceland, in Flag similarity, it says "Norway (blue cross)" instead of "Norway (blue and white cross)". I kept the mistake in the Spanish translation, for the sake of consistency.
1. Should the deck say that Ivory Coast flag is narrower (and Ireland is wider) as another difference?
1. Why add "city" to Luxembourg capital and a note that says "Officially Luxembourg"? I think it should be called Luxembourg and that's it, as it's done in Monaco. I guess it's done like that because it's written that way in the Wikipedia infobox, but can I suggest that, if we have an official link saying that the name is only Luxembourg, we change it on the Wikipedia infobox?
1. For the difference between Monaco and Indonesia flags, while keeping that Indonesia one is wider, I think it should also be said that it has a brighter red.
1. Montenegro has two capitals in the Spanish infobox: _Podgorica_ and _Cetiña_. Also, the Wikipedia Spanish page says that both are officially capitals of Montenegro, as stated by Constitution article 5. I found the [Constitution of Montenegro](http://www.skupstina.me/images/dokumenti/ustav-crne-gore.pdf) and this seems to be right (both words _Glavni grad_ and _Prijestonica_ seem to mean capital; although there could be a subtle difference in the meaning, both are in the Constitution as a kind of capitals). However, I kept Podgorica in the Spanish translation for consistency, but I think it should be changed in all languages (in the deck and the Wikipedia pages).
1. For the Netherlands, shouldn't it be said that [Netherlands](https://en.wikipedia.org/wiki/Netherlands) is a constituent country of the [Kingdom of the Netherlands](https://en.wikipedia.org/wiki/Kingdom_of_the_Netherlands)?
1. For Norway, in Flag similarity, it says "Iceland (red cross)" instead of "Iceland (red and white cross)". I kept the mistake in the Spanish translation, for the sake of consistency.
1. For Poland, in Flag similarity, it says "Indonesia and Monaco (white and red flipped)". I would change it to "Indonesia (white and red flipped, brighter red), Monaco (narrower, white and red flipped)".
1. For Kazakhstan, Capital info says "Formerly known as Astana until March 2019." I'm not sure if that's the case for English, but in Spanish this sentence is incorrect as you have indicated time twice ("formerly" and "until March 2019"), so I had to translate it without "formerly". I guess that's the case for French, too, as it's translated the same way.
1. For Cape Verde, Country info:fr is empty. I guess it's because it's not called that way ever in French, but it's strange as it's part of the official name. I left empty Country info:es as it's already called that way in Spanish.
1. For South Africa, the English capital is put as Pretoria with some capital info explaining that there are three capitals with legislative, executive and judicial power. In Spanish capital, I put Pretoria for consistency and translated the capital info, but the Wikipedia infobox says: "Ciudad del Cabo (legislativa), Pretoria (ejecutiva), Bloemfontein (judicial)". Also, I think the three cities should be mentioned in the usual order of branches of government: legislative, executive and judicial.
1. For Eswatini, the English capital is put as Mbabane with some capital info explaining that there are two capitals. In Spanish capital, I put Mbabane for consistency and translated the capital info, but Spanish and English Wikipedia list both as capitals in the infobox. I think this should be changed in the deck.
1. For Sahrawi Republic, the English capital is put as El Aaiún with some capital info explaining that there are two capitals. In Spanish capital, I put El Aaiún for consistency and translated the capital info, but Spanish and English Wikipedia list both as capitals in the infobox. I think this should be changed in the deck.
1. Some issues with Canary Islands:
    1. Flag is not the same in Spanish and English wiki. This is a good reason for always following the English wikipedia.
	1. Capitals are now written as Las Palmas de Gran Canaria and Santa Cruz de Tenerife in both wikis (and that's the official name, not only Santa Cruz and Las Palmas).
1. For Malaysia, the capital is put as Kuala Lumpur, but wikipedia says there are two capitals.
1. For Palestine, the capital is put as Ramallah, but Spanish wikipedia says there are two capitals and English wikipedia says there is a proclamed capital and an administrative center. What a mess!
1. Yemen seem to have two capital in the infobox now, in Spanish and English. I only translated the English capital for consistency.
1. Guinea is also known as Guinea-Conakry (analogously to Guinea-Bissau).
1. Azores has three capitals in Spanish Wikipedia (and English Wikipedia as well).
1. Flag of French Guiana is missing.
1. Montserrat has now three capitals according to Wikipedia.
1. Why England has as Capital hint "Not a sovereign country" while Aruba has "Constituent country"?
1. Kaliningrad oblast > Country info:nb is missing.
1. In European Union, I think we should put Brussels as the Capital. In fact, it's already done in French translation.
1. In Gulf of Thailand, I think it should be mentioned the alternative name Gulf of Siam. In fact, I think it's already done in Country info:nb.
1. In British Indian Ocean Territory, every language has a different capital.
1. Saint Martin and Saint Barthélemy have their own flags in Spanish Wikipedia. Maybe we should put them in English Wikipedia and the deck?


My suggestion for fixing them is as follows:

1. Opening an issue for discussion.
1. Opening an issue for discussion.
1. Opening an issue for discussion.
1. Fixing it for all languages (it's correct in Faroe Islands, so it can just be copied from there).
1. Fixing it for all languages, I can infer how it's done from other translations.
1. Changing it in the Wikipedia infobox (I need to find a link for reference it) and deleting "city".
1. Adding "brighter red" and translating it to all languages (I think I can infer from other translations).
1. Changing it in Wikipedia English page (I can only do it in English wiki, sorry, as it might need some discussion) and all languages of the deck.
1. Opening an issue for discussion.
1. Fixing it for all languages (it's correct in Faroe Islands, so it can just be copied from there).
1. Changing it in all languages.
1. Removing "formerly" from English, too.
1. Doing nothing, I guess it's already fine.
1. Changing it in the Wikipedia English page and in the deck for consistency with the Spanish wiki (and reality).
1. Listing two capitals in the deck.
1. Listing two capitals in the deck.
1. Doing:
    1. Nothing.
	1. Changing it in the deck.
1. Changing it in the deck in all languages.
1. Opening an issue for discussion.
1. Listing both capital in the deck in all languages.
1. Adding "Also known as Guinea-Conakry" in Country info.
1. Adding other two capitals in the deck in Capital field.
1. Adding the flag to the deck.
1. Adding all capitals to the deck in Capital field.
1. Changing one of them for consistency.
1. Opening an issue calling for a translator.
1. Putting Brussels as the Capital in all languages.
1. Adding a note similar to the one of sea of Cortez.
1. Opening an issue for discussion.
1. Opening an issue for discussion.

Keep in mind that there are a lot of things that can be outdated, as I started writing this when I started the translation and Wikipedia has changed since. In fact, I think there was a big change in all infoboxes because they mostly list all capitals now in English Wikipedia. I think all countries with more than a capital (usually put in capital info) should be revised and all the capitals put in "Capital" field. I wrote down all cases I saw from a point on, but not from the beginning (when I started looking at this, South Africa had three capitals in Spanish Wikipedia infobox and one capital in English Wikipedia infobox, but now they both have three).

A final reflection: I think the deck should follow what English Wikipedia says, even though it can oppose other Wikipedia pages. If one finds a disagreement, it should be resolved in all wikis or, at least, the most international one, the English version, as I will try to do with the multiple capital countries. I think the translations should be only translations and the content should be consistent, in my opinion. =)

**Comment by aplaice** [comment] 2020-02-09 22:02
Thanks for bringing all these up!

> OK, so get ready for a long reply. The following is copied from the document I did while translating. I think we should discuss this after merging the PR, anyway.
>

Proportionately long reply incoming! :p

> While doing the Spanish translation, I found the following issues. Some of them are very straightforward to fix, but others are more difficult.
>
> 1.  Some strings do not come from a translation (I think some of them make sense, but I don't understand most of them and I wonder why they are there):

Most of these are due to there being several alternative, equivalent names for certain geographic areas in Norwegian and German.

>     36. British Indian Ocean Territory \> Capital hint:de

This one is because in the German version of the deck, the capital of the British Indian Ocean Territory is also London, so a capital hint is needed to distinguish it from England and the UK.

> 2.  There are some sentences ended with a period and some that are not in the same field, without consistency. Which fields should end with a period and which of them shouldn't?

AFAICT:

Shouldn't end in a period (single word, short phrase or list):

* Country
* Capital
* Capital hint
* Flag similarity

Should end in a period (often a complete sentence):

* Country info
* Capital info

(It is often the case that the Country and Capital infos also aren't actually full, grammatical sentences, but for consistency I think it's best if they all end in a full stop.)

> 3.  There are some flag similarities where all countries are separated by commas and some other where the last country is separated by "and". I translated the exact English string, but other languages use always commas even if the English string doesn't.
>

I think in the English, for three countries we consistently use "X, Y and Z", but for two countries we do seem to vacillate between "X, Y" (for the Faroe Islands, Iceland and Norway) and "X and Y" (for Indonesia, Monaco and Poland).  I'm not sure which form is better.  Regarding translations, it seems that the German mostly follows the English in terms of using "and" rather than a comma, the Norwegian occasionally does, and the French just uses commas everywhere.  Since there might be conventions for how to present lists in different languages, I'm not certain whether it's worth trying to introduce full consistency.

> 4.  For Iceland, in Flag similarity, it says "Norway (blue cross)" instead of "Norway (blue and white cross)". I kept the mistake in the Spanish translation, for the sake of consistency.
>

I think that since both Norway's and Iceland's flags have the same white intermediate element it's not necessary to point out that the cross is blue and white.

> 5.  Should the deck say that Ivory Coast flag is narrower (and Ireland is wider) as another difference?
>

You're right, the Ivory Coast flag is 2:3, while the Irish one is 1:2. This is, IMO a ["minor difference"](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md#flag-similarity-field) ("slightly different geometry (e.g. width)"), so it should be mentioned.

> 6.  Why add "city" to Luxembourg capital and a note that says "Officially Luxembourg"? I think it should be called Luxembourg and that's it, as it's done in Monaco. I guess it's done like that because it's written that way in the Wikipedia infobox, but can I suggest that, if we have an official link saying that the name is only Luxembourg, we change it on the Wikipedia infobox?
>

It's also the title of the [relevant Wikipedia article](https://en.wikipedia.org/wiki/Luxembourg_City). Given that the topic of the naming of Luxembourg City [had been discussed several times already](https://en.wikipedia.org/wiki/Talk:Luxembourg_City/Archive_1#Proposed_move)), the last time in 2017, I don't think it's worth trying to change it on Wikipedia.

> 7.  For the difference between Monaco and Indonesia flags, while keeping that Indonesia one is wider, I think it should also be said that it has a brighter red.

You're right! The difference in [CIELAB ΔE*](https://en.wikipedia.org/wiki/Color_difference#CIELAB_%CE%94E*), of the two reds, using [@axelboc's spreadsheet](https://github.com/axelboc/anki-ultimate-geography/issues/50#issuecomment-525902404), is 30.02. Hence, again according to the [flag similarity guidelines](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md#flag-similarity-field), the difference is not "negligible" (30.02 ≥ 30 :p), and so should be mentioned. I think that the difference in shade of red between the Polish and Indonesian flags should also be mentioned.

| Country   | RGB (according to Wikimedia SVG) |
|-----------|----------------------------------|
| Indonesia | FF0000                           |
| Monaco    | CE1126                           |
| Poland    | DC143C                           |

The ΔEs:

| Country pair     | ΔE*   |
|------------------|-------:
| Indonesia-Monaco | 30.02 |
| Indonesia-Poland | 35.44 |
| Monaco-Poland    | 9.76  |

> 8.  Montenegro has two capitals in the Spanish infobox: *Podgorica* and *Cetiña*. Also, the Wikipedia Spanish page says that both are officially capitals of Montenegro, as stated by Constitution article 5. I found the [Constitution of Montenegro](http://www.skupstina.me/images/dokumenti/ustav-crne-gore.pdf) and this seems to be right (both words *Glavni grad* and *Prijestonica* seem to mean capital; although there could be a subtle difference in the meaning, both are in the Constitution as a kind of capitals). However, I kept Podgorica in the Spanish translation for consistency, but I think it should be changed in all languages (in the deck and the Wikipedia pages).

It might be worth bringing up on the Wikipedia page. The last discussion that I could find was [from February 2007](https://en.wikipedia.org/wiki/Talk:Montenegro/Archive_2#Capital), when the current constitution was only in draft form (it was officially passed in October 2007), though

I would definitely argue in favour of adding Cetiña to the Spanish "Capital info" as the "Antigua Capital Real" (since it's in the infobox).

Adding Cetinje to the English "Capital info" as the "Old Royal Capital" might also be a good idea.

([According to Encyclopaedia Britannica](https://www.britannica.com/place/Montenegro):

> Capital: Podgorica; Cetinje is the Old Royal Capital

)

> 9.  For the Netherlands, shouldn't it be said that [Netherlands](https://en.wikipedia.org/wiki/Netherlands) is a constituent country of the [Kingdom of the Netherlands](https://en.wikipedia.org/wiki/Kingdom_of_the_Netherlands)?

Technically yes, though it feels a bit silly. (Denmark is in a very similar situation.)

> 10. For Norway, in Flag similarity, it says "Iceland (red cross)" instead of "Iceland (red and white cross)". I kept the mistake in the Spanish translation, for the sake of consistency.
>

See 4.

> 11. For Poland, in Flag similarity, it says "Indonesia and Monaco (white and red flipped)". I would change it to "Indonesia (white and red flipped, brighter red), Monaco (narrower, white and red flipped)".

I agree (see 7.).

> 12. For Kazakhstan, Capital info says "Formerly known as Astana until March 2019." I'm not sure if that's the case for English, but in Spanish this sentence is incorrect as you have indicated time twice ("formerly" and "until March 2019"), so I had to translate it without "formerly". I guess that's the case for French, too, as it's translated the same way.

I don't think it's incorrect in English, but it's redundant and could be changed.

> 13. For Cape Verde, Country info:fr is empty. I guess it's because it's not called that way ever in French, but it's strange as it's part of the official name. I left empty Country info:es as it's already called that way in Spanish.

From what I recall when I looked into this at the time, no official French bodies, nor the French media use or acknowledge the name Cabo Verde, so it shouldn't be in the French translation.

> 14. For South Africa, the English capital is put as Pretoria with some capital info explaining that there are three capitals with legislative, executive and judicial power. In Spanish capital, I put Pretoria for consistency and translated the capital info, but the Wikipedia infobox says: "Ciudad del Cabo (legislativa), Pretoria (ejecutiva), Bloemfontein (judicial)". Also, I think the three cities should be mentioned in the usual order of branches of government: legislative, executive and judicial.

Ugh. The infobox in English Wikipedia also says "Pretoria (executive), Bloemfontein (judicial), Cape Town (legislative)" (as do the German, French and Norwegian ones), so the same solution should be used for all of them.  (Encyclopaedia Britannica also gives the three cities as capitals...)

The two possible approaches are:

1. (The current, de-facto approach.) Give the first city in the infobox as the "capital", and mention the remaining ones in the "Capital info".
2. List all the cities as capitals.

I don't have any strong opinion on whether the current approach should be kept or not. This should probably go in its own issue...

> 15. For Eswatini, the English capital is put as Mbabane with some capital info explaining that there are two capitals. In Spanish capital, I put Mbabane for consistency and translated the capital info, but Spanish and English Wikipedia list both as capitals in the infobox. I think this should be changed in the deck.

(See 14.)

> 16. For Sahrawi Republic, the English capital is put as El Aaiún with some capital info explaining that there are two capitals. In Spanish capital, I put El Aaiún for consistency and translated the capital info, but Spanish and English Wikipedia list both as capitals in the infobox. I think this should be changed in the deck.

(See 14.)

> 17. Some issues with Canary Islands:
>     
>     1.  Flag is not the same in Spanish and English wiki. This is a good reason for always following the English wikipedia.

I think that this is a case where one wiki uses the "state" flag and the other the "civil" flag. (See also #111.) Since having separate media for different languages would be messy, I agree that in this case (flag images) one should follow English Wikipedia, but I don't necessarily agree that one should follow it for all fields, for all languages.

>     2.  Capitals are now written as Las Palmas de Gran Canaria and Santa Cruz de Tenerife in both wikis (and that's the official name, not only Santa Cruz and Las Palmas).

This seems to be contradicting our otherwise de-facto policy of listing the first city from the infobox, though the situation is slightly different, since it appears that the two capitals have the same status...

> 18. For Malaysia, the capital is put as Kuala Lumpur, but wikipedia says there are two capitals.
>

(See 14.)

> 19. For Palestine, the capital is put as Ramallah, but Spanish wikipedia says there are two capitals and English wikipedia says there is a proclamed capital and an administrative center. What a mess\!

(See 14.)

> 20. Yemen seem to have two capital in the infobox now, in Spanish and English. I only translated the English capital for consistency.

(See 14.)

> 21. Guinea is also known as Guinea-Conakry (analogously to Guinea-Bissau).

According to Wikipedia it's "sometimes" referred to as Guinea-Conakry, so this could be mentioned in the "Country info", but IMO it's not essential.

> 22. Azores has three capitals in Spanish Wikipedia (and English Wikipedia as well).

(14.)

> 23. Flag of French Guiana is missing.

This was probably because subdivisions of France generally don't officially have their own flags, but it seems that the French Guianese General Council adopted one in 2010. OTOH, according to [the dedicated article on the flag](https://en.wikipedia.org/wiki/Flag_of_French_Guiana) the body that had adopted the flag was disbanded in 2015...

> 24. Montserrat has now three capitals according to Wikipedia.

In this case, the official capital was destroyed (as described in the "Capital info") and the capital under construction is still under construction, so keeping the de facto capital Brades for the time being should be OK.

Little Bay could be mentioned in the "Capital info".

> 25. Why England has as Capital hint "Not a sovereign country" while Aruba has "Constituent country"?

Aruba's hint can't be "Not a sovereign country" because that would fail to distinguish it from Sint Eustatius, which is also "Not a sovereign country". In general, though, we [prefer maximally-generic hints](https://github.com/axelboc/anki-ultimate-geography/issues/179#issuecomment-565804521), which is why England's hint isn't "Constituent country".

> 26. Kaliningrad oblast \> Country info:nb is missing.

True.

> 27. In European Union, I think we should put Brussels as the Capital. In fact, it's already done in French translation.

I agree! :) (The main counter-argument would be that the EU isn't a country, but if we can have capitals for subdivisions, then there's no reason not to have one for the EU.)

> 28. In Gulf of Thailand, I think it should be mentioned the alternative name Gulf of Siam. In fact, I think it's already done in Country info:nb.

Makes sense.

> 29. In British Indian Ocean Territory, every language has a different capital.

That's a known issue, though it's a consequence of following each language's Wikipedia article, and I'm not 100 % sure that it's really an issue.

> 30. Saint Martin and Saint Barthélemy have their own flags in Spanish Wikipedia. Maybe we should put them in English Wikipedia and the deck?

I don't think that they're actually officially recognised. (23. is related.) OTOH that doesn't necessarily mean that these flags couldn't be added.

<hr/>

> My suggestion for fixing them is as follows:
>
> 1.  Opening an issue for discussion.

Perhaps.

> 2.  Opening an issue for discussion.

Yeah, I think that we have a convention, but if there are inconsistencies, these should be ironed out.

> 3.  Opening an issue for discussion.

Perhaps.

> 4.  Fixing it for all languages (it's correct in Faroe Islands, so it can just be copied from there).

Not sure. Could open an issue for discussion.

> 5.  Fixing it for all languages, I can infer how it's done from other translations.

Definitely!

> 6.  Changing it in the Wikipedia infobox (I need to find a link for reference it) and deleting "city".

Not sure. (Change unlikely to be accepted on Wikipedia.)

> 7.  Adding "brighter red" and translating it to all languages (I think I can infer from other translations).

Definitely yes!

> 8.  Changing it in Wikipedia English page (I can only do it in English wiki, sorry, as it might need some discussion) and all languages of the deck.

I think I agree, but good luck pushing it through...

> 9.  Opening an issue for discussion.

Yeah.

> 10. Fixing it for all languages (it's correct in Faroe Islands, so it can just be copied from there).

Not sure (see 4.).

> 11. Changing it in all languages.

Definitely!

> 12. Removing "formerly" from English, too.

I agree.

> 13. Doing nothing, I guess it's already fine.

I think so too.

> 14. Changing it in the Wikipedia English page and in the deck for consistency with the Spanish wiki (and reality).
> 15. Listing two capitals in the deck.
> 16. Listing two capitals in the deck.
> 18. Changing it in the deck in all languages.
> 19. Opening an issue for discussion.
> 20. Listing both capital in the deck in all languages.
> 22. Adding other two capitals in the deck in Capital field.
> 24. Adding all capitals to the deck in Capital field.

I think these should all be discussed together, in an issue.

> 17. Doing:
>     1.  Nothing.

Yeah.

>     2.  Changing it in the deck.

Probably.

> 21. Adding "Also known as Guinea-Conakry" in Country info.

I'm not entirely convinced.

> 23. Adding the flag to the deck.
> 30. Opening an issue for discussion.

I think these two should go in their own issue, for further discussion.

> 25. Changing one of them for consistency.

In this case the discrepancy is deliberate, so no.

> 26. Opening an issue calling for a translator.

I think so.

> 27. Putting Brussels as the Capital in all languages.

Yes! :)

> 28. Adding a note similar to the one of sea of Cortez.

Yes!

> 29. Opening an issue for discussion.

I'm not sure.

>
> Keep in mind that there are a lot of things that can be outdated, as I started writing this when I started the translation and Wikipedia has changed since. In fact, I think there was a big change in all infoboxes because they mostly list all capitals now in English Wikipedia. I think all countries with more than a capital (usually put in capital info) should be revised and all the capitals put in "Capital" field. I wrote down all cases I saw from a point on, but not from the beginning (when I started looking at this, South Africa had three capitals in Spanish Wikipedia infobox and one capital in English Wikipedia infobox, but now they both have three).


> A final reflection: I think the deck should follow what English Wikipedia says, even though it can oppose other Wikipedia pages. If one finds a disagreement, it should be resolved in all wikis or, at least, the most international one, the English version, as I will try to do with the multiple capital countries. I think the translations should be only translations and the content should be consistent, in my opinion.  =)

I think this is a very interesting question of to what extent the different language versions should be simple translations and to what extent independent decks.

My personal stance is that in case of doubt we should sway towards consistency, but not enforce it absolutely. (This might lead to unnecessary complexity, though.)

Thanks again!

**Comment by aplaice** [comment] 2020-02-10 23:01
Also, since I forgot earlier, good luck with your thesis defence, if you haven't had it already!

**Comment by axelboc** [comment] 2020-02-17 09:06
3\. Commas in flag similarities => issue #203
5\. Width of Ivory Coast and Ireland flags => issue #204
7\. Colour Monaco, Poland and Indonesia flags => issue #204
8\. Secondary capital of Montenegro => issue #205
12\. "Formerly" in Kazakhstan's capital info => issue #206
14\. Capital of South Africa in Spanish => issue #207
15\. 16. 17. 18. 19. 20. Not sure about Canary Islands, but let's discuss all this in #207
26\. Kaliningrad Oblast capital info in Dutch => see issue #208

Running out of time, I'll finish this up tonight ;)

**Comment by josealberto4444** [comment] 2020-02-17 13:30
> On returning to this later, I apologise if any of the above came out sounding harsh. These were obviously purely my opinions and I don't want to torpedo any of your ideas!

Not at all! I understand it's a long reply and it's tiring to write it the long and kind way, hehe. I had the same sensation when writing my initial comment. =) I didn't answer to your comment because I haven't been able to do it until now. I have very few free time. =(

> Also, since I forgot earlier, good luck with your thesis defence, if you haven't had it already!

Thank you very much! It's on mid April. =)

> Running out of time, I'll finish this up tonight ;)

OK, I'll take a look at all the info and I will be able to fix some issues around next week, probably.

Thank you both! ^^

**Comment by axelboc** [comment] 2020-02-17 19:23
First of all, @josealberto4444, thanks a lot for all these notes, and thanks @aplaice for your review! 🏆 

If an item is not listed below, it's because I agree with @aplaice's reply. I've opened issues when a change is definitely required or when further discussions are needed. Feel free to open some more, of course. 😉 

3\. Commas in flag similarities => issue #203
5\. Width of Ivory Coast and Ireland flags => issue #204
7\. Colour Monaco, Poland and Indonesia flags => issue #204
8\. Secondary capital of Montenegro => issue #205
12\. "Formerly" in Kazakhstan's capital info => issue #206
14\. Capital of South Africa in Spanish => issue #207
15\. 16. 17. 18. 19. 20. Not sure about Canary Islands, but let's discuss all this in #207
24\. Capital of Montserrat => To avoid changing it again later, I don't think it's worth mentioning Little Bay until it becomes the new capital.
26\. Kaliningrad Oblast capital info in Dutch => issue #208
27\. European Union capital => Not sure about this one (see below). 
28\. Alternative name for Gulf of Thailand => issue #209

---

Here are my thoughts regarding the capital of the EU:

- First, it seems like a shame to have to add capital hints to distinguish Belgium from the European Union.
- Second, it's not a straightforward change:
  - Although English Wikipedia mentions Brussels as the capital in the info box, French Wikipedia doesn't and instead lists the various institutions, so the French translation would have to not have the capital.
  - One of the institutions, the Parliament, is located in Strasbourg, so should this city be considered a secondary capital and mentioned in the _Capital info_ field?

I feel like we keep trying to fit a square peg in a round hole. Maybe the current model of using the _Country - Capital_ and _Capital - Country_ templates for subdivisions, along with capital hints, has reach its limit and we should brainstorm an alternative? I don't know, maybe we could add a new template, or decide that if a subdivision's capital conflicts with a sovereign country's capital, we simply don't add it. After all, this is what we do with flags (e.g. we don't have a flag for French Guiana _because_ it's the French flag). Anyway, just a thought for now. If you don't think I'm going crazy, we can discuss further this in a separate issue.

**Comment by axelboc** [comment] 2020-02-17 19:30
Closing this issue now, since its main purpose was achieved! 💯 

Feel free to keep commenting here, or to open new issues as appropriate. Also, feel free to take on any of the issues I've just opened, as I won't have time myself. Thanks again!

**Closed by axelboc** 2020-02-17 19:30 UTC
Labels: translation
