### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by bjkgit** [axelboc/anki-ultimate-geography#311] opened 2020-05-17 00:10 UTC
This deck crashes my iphone anki app. When I use the deck, the app occasionally (every few cards) exists.  

This doesn’t happen with my many other shared decks. Doesn’t seem to be any problems with the database.

**Comment by aplaice** [comment] 2020-05-17 01:01
Thanks for reporting!

I'm very sorry that that is happening.

However,

**Comment by aplaice** [comment] 2020-05-17 01:30
Thanks for telling us!

I'm very sorry that this is happening.

Have you reported this to [the Anki tenderapp](https://apps.ankiweb.net/docs/help.html)? 

Damien is far more likely to be able to help than us — the main maintainers/contributors to this deck don't use iOS devices, so we have a very limited ability to troubleshoot. (I have an ancient iPad, with a very old version of Anki, which I occasionally use for testing this deck (though I have never encountered any crashes) but that's unlikely to be helpful.)

Also, this deck doesn't use any "weird", unsupported features (in particular it doesn't use any JavaScript, which AFAIR is the only "feature" that's [advertised as unsupported](https://docs.ankiweb.net/#/templates/styling?id=javascript)), so there's no reason it should cause crashes. (Hence, it's possible that it's a bug in Ankimobile.)

<hr/>

Alternatively, if you're willing we could try to determine the issue here, by asking you for further details, but that's likely to be very hit-and-miss.

(For instance, can you tell us anything about which cards the crashes occur on? Are they the same cards? The same card types? Alternatively the same notes?

When did the crashes start — from the first time you used the deck or after an update? Which version of the deck do you have?)

<hr/>

(Sorry for temporarily closing opening the issue — it's extremely late here and I had pressed the wrong button...)

**Comment by axelboc** [comment] 2020-05-17 08:33
Strange... As @aplaice, I don't have any experience with the iOS app, but on Android, I would have suggested to delete the deck on your phone, hit sync and select the option to force a re-download of the whole deck from your Anki account.

**Comment by bjkgit** [comment] 2020-05-19 11:53
Hi, 

Thanks for your quick answers.  I am using all new products.  My iOS is 13.4.1, which is the newest.  My Anki is 2.0.63 (20063.6).  My Ultimate Geography is v3.3.  

Here is a sequence that caused many "crashes". When I say it "crashes", I mean that the Anki display disappears from the screen and I see the iPhone desktop with the many app icons on it again.  But I can check and see that the app is still open in the memory of the iPhone, so it doesn't completely crash. 

1)  First, I did Anki on 4 of my previous decks without any problem. 
2) Next, I switched to Ultimate Geography, and ran through several cards in this order : 
	i) the flag of Romania
	ii) the name of Poland
	iii) the flag of Romania
	iv) the name of Melilla

The first 3 worked, and then after I clicked "green" that I recognize Melilla, the app "crashes". 

3) Next, I open Anki again. I go to one of my previous decks and do a few cards and it works, so the Anki app itself does not appear to be corrupted. 

4) But then I go to the Ultimate Geography deck. 
	i) The capital of Romania is ...
		I click to see the answer is Bucharest. 
	When I click on the green button, Anki "crashes". 

5) So I open Anki again, go to Ultimate Geography, and click "Browse".  Then Anki "crashes", 

6) At this point, it is clear that no matter what I do on Anki with Ultimate Geography, the Anki display will "crash".  So I stop and restart Anki completely.  My other decks work, so I click on Ultimate Geography. 
	i) The capital of Poland is ... 
		I click to see the answer, and the Anki app once again "crashes".

7) Next, I delete the Ultimate Geography deck, and reinstall it. I set the new card threshold to 10, and start answering some cards. 
		i) Stockholm is the capital of ...    (works)
		ii)  Flag of Melilla ... 	(works)
		iii) Capital of Poland .... (works)
		iv) Capital of Romania ... (works)
		v) Gulf of Thailand ... 	(doesn't work .... Anki display closes)

Now, the Anki Ultimate Geography deck is corrupted, and I would have to reinstall the deck to make it work again.  

---

Its hard for me to imagine that this is a problem with your deck, except that it only happens with your deck :)

Perhaps this is a general question for Anki to do with iPhones. If so, I can stop using this thread, and switch it to another. 



Thanks,
Ben

**Comment by aplaice** [comment] 2020-06-06 21:21
Thank you very much for the highly detailed description of the crashes and sorry for the extremely late answer!

Unfortunately, the behaviour doesn't seem to be deterministic (in particular the displaying of the answer on the Country->Capital card for Poland sometimes crashing and sometimes not). It also doesn't seem to be caused by any media (our images being somehow incompatible with iOS), which I was both hoping for and dreading (hoping since it'd make debugging easier, dreading since our images being incompatible with iOS would have been a catastrophe). 

As a result, I don't see what part of our deck in particular might be the cause of the crashes. I'd guess that it's probably a database issue, but I have no idea how to debug further.

I'm sorry that I couldn't be of more help.

> Perhaps this is a general question for Anki to do with iPhones. If so, I can stop using this thread, and switch it to another.

I'd strongly recommend that, if you have the time and inclination!

**Comment by axelboc** [comment] 2020-06-21 10:14
The v4 will be released very soon. Please let us know if you're having any issue upgrading.

If performing a [clean import](https://github.com/axelboc/anki-ultimate-geography#major-version) doesn't cut it, I'd recommend creating a new Anki profile, importing your decks' APKGs in there, and doing an in-depth clean up of your Anki Web account before synchronising everything again. If that doesn't work either, I'd add to the mix creating a new Anki Web account and uninstalling/reinstalling all your apps (desktop and mobile).

Good luck!!

**Closed by axelboc** 2020-06-21 10:14 UTC
